# irci/email_sender.py
"""
Email delivery for IRCI reports.

Supports:
- SMTP email sending
- SendGrid API (if configured)
- Attachment of PDF reports
"""
from __future__ import annotations
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from typing import Optional, List
from datetime import datetime

from .logging import get_logger

log = get_logger("irci.email")


def send_email_smtp(
    to_emails: List[str],
    subject: str,
    body_html: str,
    attachments: Optional[List[tuple]] = None,
    smtp_server: str = None,
    smtp_port: int = None,
    smtp_user: str = None,
    smtp_password: str = None,
    from_email: str = None
) -> dict:
    """
    Send email via SMTP.

    Args:
        to_emails: List of recipient email addresses
        subject: Email subject
        body_html: HTML body content
        attachments: List of (filename, bytes_data) tuples
        smtp_server: SMTP server hostname
        smtp_port: SMTP port (default 587 for TLS)
        smtp_user: SMTP username
        smtp_password: SMTP password
        from_email: From email address

    Returns:
        Dict with success status and message
    """
    # Get credentials from environment if not provided
    smtp_server = smtp_server or os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = smtp_port or int(os.getenv("SMTP_PORT", "587"))
    smtp_user = smtp_user or os.getenv("SMTP_USER", "")
    smtp_password = smtp_password or os.getenv("SMTP_PASSWORD", "")
    from_email = from_email or os.getenv("SMTP_FROM", smtp_user)

    if not smtp_user or not smtp_password:
        return {
            "success": False,
            "error": "SMTP credentials not configured. Set SMTP_USER and SMTP_PASSWORD environment variables."
        }

    try:
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = from_email
        msg['To'] = ', '.join(to_emails)

        # Add HTML body
        msg.attach(MIMEText(body_html, 'html'))

        # Add attachments
        if attachments:
            for filename, data in attachments:
                attachment = MIMEApplication(data, Name=filename)
                attachment['Content-Disposition'] = f'attachment; filename="{filename}"'
                msg.attach(attachment)

        # Send via SMTP
        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.sendmail(from_email, to_emails, msg.as_string())

        log.info(f"Email sent successfully to {to_emails}")
        return {"success": True, "message": f"Email sent to {', '.join(to_emails)}"}

    except Exception as e:
        log.error(f"Failed to send email: {e}")
        return {"success": False, "error": str(e)}


def send_irci_report_email(
    to_email: str,
    ticker: str,
    quarter: str,
    pdf_data: bytes,
    irci_score: float = None,
    summary: str = None
) -> dict:
    """
    Send an IRCI report email with PDF attachment.

    Args:
        to_email: Recipient email address
        ticker: Primary ticker symbol
        quarter: Quarter string (e.g., '2024Q3')
        pdf_data: PDF report as bytes
        irci_score: Optional IRCI composite score
        summary: Optional analysis summary

    Returns:
        Dict with success status and message
    """
    subject = f"IRCI Analysis Report: {ticker} - {quarter}"

    # Build HTML body
    score_text = f"<strong>IRCI Score: {irci_score:.0f}%</strong><br><br>" if irci_score else ""
    summary_text = f"<p><strong>Summary:</strong><br>{summary}</p>" if summary else ""

    body_html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #2c3e50;">IRCI Analysis Report</h2>
        <p>
            <strong>Company:</strong> {ticker}<br>
            <strong>Quarter:</strong> {quarter}<br>
            <strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}
        </p>
        {score_text}
        {summary_text}
        <p>Please find your detailed IRCI analysis report attached as a PDF.</p>
        <hr style="border: 1px solid #eee; margin: 20px 0;">
        <p style="color: #666; font-size: 12px;">
            This report was generated by IRCI (Investor Relations Contribution Index).<br>
            For questions, contact your IR team.
        </p>
    </body>
    </html>
    """

    filename = f"IRCI_Report_{ticker}_{quarter}.pdf"

    return send_email_smtp(
        to_emails=[to_email],
        subject=subject,
        body_html=body_html,
        attachments=[(filename, pdf_data)]
    )


def validate_email(email: str) -> bool:
    """Simple email validation."""
    import re
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return bool(re.match(pattern, email))


def get_email_config_status() -> dict:
    """
    Check if email is configured.

    Returns:
        Dict with configuration status
    """
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_password = os.getenv("SMTP_PASSWORD", "")

    if smtp_user and smtp_password:
        return {
            "configured": True,
            "provider": "SMTP",
            "user": smtp_user[:3] + "***" if len(smtp_user) > 3 else "***"
        }
    else:
        return {
            "configured": False,
            "message": "Set SMTP_USER and SMTP_PASSWORD to enable email delivery"
        }
